const admin = require('firebase-admin');
const crypto = require('crypto');
const { getFirestore, initFirebaseAdmin } = require('./fcm');

const C={posts:'bulletin_posts',polls:'bulletin_polls',reports:'bulletin_reports',requests:'bulletin_content_requests',bans:'bulletin_bans',blocks:'bulletin_blocks',config:'bulletin_config',moderation:'bulletin_moderation_events',users:'users'};
const categories=['daily','knowledge','relationship'];
const publishers=[
  {id:'tombik_teyze',displayName:'Tombik Teyze',avatarUrl:'',verified:true},
  {id:'serdar',displayName:'Serdar Çakır',avatarUrl:'',verified:true},
  {id:'hatice',displayName:'Hatice',avatarUrl:'',verified:true},
];
const limits={title:140,summary:300,body:12000,comment:1500,page:15};
const obviousTerms=['orospu','siktir','amına','amina','piç','pic','yarrak'];
function db(){if(!initFirebaseAdmin()||!getFirestore())throw Object.assign(new Error('Firestore kullanılamıyor.'),{statusCode:503});return getFirestore();}
function fail(message,statusCode=400,code='invalid_request'){throw Object.assign(new Error(message),{statusCode,code});}
function clean(v){return String(v||'').trim();}
function normalize(v){return clean(v).toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[013457@$]/g,x=>({'0':'o','1':'i','3':'e','4':'a','5':'s','7':'t','@':'a','$':'s'}[x])).replace(/(.)\1{2,}/g,'$1$1').replace(/[^a-zçğıöşü]+/gi,' ').replace(/\s+/g,' ').trim();}
async function blockedTerms(){const s=await db().collection(C.config).doc('moderation').get();return [...obviousTerms,...((s.data()?.blockedTerms||[]).map(clean).filter(Boolean))];}
async function moderate(text){const n=normalize(text),compact=n.replace(/\s/g,'');for(const raw of await blockedTerms()){const term=normalize(raw);if(!term)continue;const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');if(new RegExp(`(^|\\s)${escaped}(\\s|$)`,'i').test(n)||(term.length>=4&&compact.includes(term.replace(/\s/g,''))))fail('Yorum topluluk kurallarına aykırı ifade içeriyor.',422,'content_rejected');}}
function youtubeId(url){const value=clean(url);if(!value)return null;try{const u=new URL(value.startsWith('http')?value:`https://${value}`);const host=u.hostname.replace(/^www\./,'').toLowerCase();let id=null;if(host==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0];else if(host==='youtube.com'||host==='m.youtube.com'){if(u.pathname==='/watch')id=u.searchParams.get('v');else{const p=u.pathname.split('/').filter(Boolean);if(['shorts','embed','live'].includes(p[0]))id=p[1];}}return /^[A-Za-z0-9_-]{11}$/.test(id||'')?id:null;}catch(_){return null;}}
function istanbulEndOfDay(now=Date.now()){const shifted=new Date(now+3*3600000);const next=Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate()+1)-3*3600000;return admin.firestore.Timestamp.fromMillis(next);}
function millis(v){return v?.toMillis?.()||v||null;}
function postJson(doc,liked=false){const d=doc.data();return{id:doc.id,title:d.title||'',summary:d.summary||'',body:d.body||'',categoryIds:d.categoryIds||[],authorId:d.authorId,authorDisplayName:d.authorDisplayName,authorAvatarUrl:d.authorAvatarUrl||'',authorVerified:d.authorVerified===true,mediaType:d.mediaType||'none',imageUrl:d.imageUrl||null,youtubeVideoId:d.youtubeVideoId||null,youtubeUrl:d.youtubeUrl||null,youtubeThumbnailUrl:d.youtubeThumbnailUrl||null,status:d.status,createdAt:millis(d.createdAt),publishedAt:millis(d.publishedAt),scheduledFor:millis(d.scheduledFor),updatedAt:millis(d.updatedAt),dailyVisibilityUntil:millis(d.dailyVisibilityUntil),likeCount:Number(d.likeCount)||0,commentCount:Number(d.commentCount)||0,allowComments:d.allowComments!==false,allowLikes:d.allowLikes!==false,allowShare:d.allowShare!==false,liked};}
function commentJson(doc){const d=doc.data();return{id:doc.id,postId:d.postId,userId:d.userId,displayName:d.displayName||'Bülten Okuru',body:d.body||'',createdAt:millis(d.createdAt),moderationStatus:d.moderationStatus||'published'};}
async function isBanned(uid){return (await db().collection(C.bans).doc(uid).get()).exists;}
async function safeName(uid){const d=(await db().collection(C.users).doc(uid).get()).data()||{};return clean(d.displayName||d.name||'Bülten Okuru').slice(0,50);}
function cursor(doc){return doc?Buffer.from(JSON.stringify({id:doc.id,t:doc.get('publishedAt')?.toMillis?.()||0})).toString('base64url'):null;}
async function feed(uid,{category='daily',cursor:after,limit=15}={}){if(!categories.includes(category))fail('Geçersiz kategori.');const n=Math.min(20,Math.max(1,Number(limit)||limits.page));let q=db().collection(C.posts).where('status','==','published').where('categoryIds','array-contains',category).orderBy('publishedAt','desc').orderBy(admin.firestore.FieldPath.documentId(),'desc');if(after){try{const c=JSON.parse(Buffer.from(after,'base64url'));q=q.startAfter(admin.firestore.Timestamp.fromMillis(c.t),c.id);}catch(_){fail('Geçersiz sayfalama anahtarı.');}}const snap=await q.limit(category==='daily'?Math.min(40,n*2):n).get();let docs=snap.docs;if(category==='daily')docs=docs.filter(x=>(x.get('dailyVisibilityUntil')?.toMillis?.()||0)>Date.now());docs=docs.slice(0,n);const likes=docs.length?await Promise.all(docs.map(x=>x.ref.collection('likes').doc(uid).get())):[];return{items:docs.map((x,i)=>postJson(x,likes[i]?.exists)),nextCursor:snap.size>=n?cursor(snap.docs.at(-1)):null};}
async function detail(uid,id,commentCursor){const ref=db().collection(C.posts).doc(clean(id)),snap=await ref.get();if(!snap.exists||snap.get('status')!=='published')fail('İçerik bulunamadı.',404);const [liked,blocks]=await Promise.all([ref.collection('likes').doc(uid).get(),db().collection(C.blocks).where('ownerId','==',uid).limit(200).get()]);const blocked=new Set(blocks.docs.map(x=>x.get('blockedUserId')));let q=ref.collection('comments').where('moderationStatus','==','published').orderBy('createdAt','desc').limit(15);if(commentCursor)q=q.startAfter(admin.firestore.Timestamp.fromMillis(Number(commentCursor)));const comments=await q.get();const visible=comments.docs.filter(x=>!blocked.has(x.get('userId')));return{post:postJson(snap,liked.exists),comments:visible.map(commentJson),nextCommentCursor:comments.size===15?String(comments.docs.at(-1).get('createdAt').toMillis()):null};}
async function toggleLike(uid,id){const post=db().collection(C.posts).doc(clean(id)),like=post.collection('likes').doc(uid);let result;await db().runTransaction(async tx=>{const [p,l]=await Promise.all([tx.get(post),tx.get(like)]);if(!p.exists||p.get('status')!=='published'||p.get('allowLikes')===false)fail('Bu içerik beğenilemiyor.',409);const was=l.exists,count=Math.max(0,(Number(p.get('likeCount'))||0)+(was?-1:1));if(was)tx.delete(like);else tx.create(like,{userId:uid,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.update(post,{likeCount:count});result={liked:!was,likeCount:count};});return result;}
async function addComment(uid,id,body){if(await isBanned(uid))fail('Bülten yorum yetkiniz kaldırılmış.',403,'bulletin_banned');const text=clean(body?.body);if(text.length<2||text.length>limits.comment)fail('Yorum uzunluğu geçersiz.');await moderate(text);const post=db().collection(C.posts).doc(clean(id)),comment=post.collection('comments').doc(),name=await safeName(uid);await db().runTransaction(async tx=>{const p=await tx.get(post);if(!p.exists||p.get('status')!=='published'||p.get('allowComments')===false)fail('Bu içeriğe yorum yapılamıyor.',409);tx.create(comment,{postId:id,userId:uid,displayName:name,body:text,createdAt:admin.firestore.FieldValue.serverTimestamp(),moderationStatus:'published',reportCount:0});tx.update(post,{commentCount:admin.firestore.FieldValue.increment(1)});});return{id:comment.id};}
async function reportComment(uid,body){const postId=clean(body.postId),commentId=clean(body.commentId),reason=clean(body.reason),allowed=['Küfür / Hakaret','Taciz','Spam','Uygunsuz İçerik','Kişisel Bilgi','Diğer'];if(!postId||!commentId||!allowed.includes(reason))fail('Şikâyet bilgileri geçersiz.');const report=db().collection(C.reports).doc(`${uid}_${commentId}`),comment=db().collection(C.posts).doc(postId).collection('comments').doc(commentId);await db().runTransaction(async tx=>{const [r,c]=await Promise.all([tx.get(report),tx.get(comment)]);if(r.exists)return;if(!c.exists)fail('Yorum bulunamadı.',404);tx.create(report,{reporterId:uid,postId,commentId,commenterId:c.get('userId'),commentBody:c.get('body'),commenterName:c.get('displayName'),reason,status:'open',createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.update(comment,{reportCount:admin.firestore.FieldValue.increment(1)});});return{success:true};}
async function block(uid,targetUid){targetUid=clean(targetUid);if(!targetUid||targetUid===uid)fail('Kullanıcı engellenemedi.');await db().collection(C.blocks).doc(`${uid}_${targetUid}`).set({ownerId:uid,blockedUserId:targetUid,createdAt:admin.firestore.FieldValue.serverTimestamp()});return{success:true};}
async function submitContentRequest(uid,body){const text=clean(body?.text);if(text.length<10||text.length>1200)fail('Talep 10-1200 karakter olmalı.');await moderate(text);const user=(await db().collection(C.users).doc(uid).get()).data()||{};const ref=db().collection(C.requests).doc();await ref.set({userId:uid,displayName:clean(user.displayName||user.name||'Bülten Okuru').slice(0,50),text,status:'open',createdAt:admin.firestore.FieldValue.serverTimestamp()});return{id:ref.id};}
async function adminContentRequests(){const s=await db().collection(C.requests).orderBy('createdAt','desc').limit(200).get();return s.docs.map(x=>({id:x.id,...x.data(),createdAt:millis(x.get('createdAt'))}));}
async function adminContentRequestAction(uid,id,action){if(!['poll_candidate','dismiss'].includes(action))fail('Geçersiz işlem.');await db().collection(C.requests).doc(clean(id)).update({status:action,reviewedAt:admin.firestore.FieldValue.serverTimestamp(),reviewedBy:uid});return{success:true};}
async function activePoll(uid){const s=await db().collection(C.polls).where('status','==','active').orderBy('createdAt','desc').limit(5).get(),doc=s.docs.find(x=>(x.get('endAt')?.toMillis?.()||0)>Date.now());if(!doc)return{poll:null};const vote=await doc.ref.collection('votes').doc(uid).get(),d=doc.data();return{poll:{id:doc.id,question:d.question,options:d.options||[],startAt:millis(d.startAt),endAt:millis(d.endAt),status:d.status,totalVotes:Number(d.totalVotes)||0,userOptionId:vote.exists?vote.get('optionId'):null,confirmedWinnerOptionId:d.confirmedWinnerOptionId||null}};}
async function votePoll(uid,pollId,optionId){const poll=db().collection(C.polls).doc(clean(pollId)),vote=poll.collection('votes').doc(uid);let result;await db().runTransaction(async tx=>{const [p,v]=await Promise.all([tx.get(poll),tx.get(vote)]);if(!p.exists||p.get('status')!=='active'||(p.get('endAt')?.toMillis?.()||0)<=Date.now())fail('Anket kapalı.',409);if(v.exists)fail('Bu ankette daha önce oy kullandınız.',409,'already_voted');const options=p.get('options')||[],index=options.findIndex(x=>x.id===optionId);if(index<0)fail('Geçersiz seçenek.');options[index]={...options[index],voteCount:(Number(options[index].voteCount)||0)+1};tx.create(vote,{userId:uid,optionId,createdAt:admin.firestore.FieldValue.serverTimestamp()});tx.update(poll,{options,totalVotes:admin.firestore.FieldValue.increment(1)});result={options,totalVotes:(Number(p.get('totalVotes'))||0)+1,userOptionId:optionId};});return result;}
function publisher(id){return publishers.find(x=>x.id===id)||null;}
function validatePost(body){const title=clean(body.title),summary=clean(body.summary),text=clean(body.body),cats=[...new Set(Array.isArray(body.categoryIds)?body.categoryIds.filter(x=>categories.includes(x)):[])],media=['none','image','youtube'].includes(body.mediaType)?body.mediaType:'none',status=['draft','published','scheduled'].includes(body.status)?body.status:'draft';if(!title||title.length>limits.title||summary.length>limits.summary||text.length>limits.body||!cats.length)fail('İçerik alanları geçersiz.');const author=publisher(clean(body.authorId));if(!author)fail('Yayıncı yetkili değil.',403);let yt=null;if(media==='youtube'){yt=youtubeId(body.youtubeUrl);if(!yt)fail('Geçerli bir YouTube bağlantısı gerekli.');}const scheduledMillis=Number(body.scheduledFor)||0;if(status==='scheduled'&&scheduledMillis<=Date.now())fail('Planlanan yayın zamanı gelecekte olmalı.');return{title,summary,body:text,categoryIds:cats,mediaType:media,status,author,yt,scheduledMillis};}
async function adminSavePost(adminUid,id,body){const v=validatePost(body),ref=id?db().collection(C.posts).doc(clean(id)):db().collection(C.posts).doc(),old=(await ref.get()).data()||{},now=admin.firestore.FieldValue.serverTimestamp(),daily=v.categoryIds.includes('daily'),publishedAt=v.status==='published'?(old.publishedAt||now):null;const data={title:v.title,summary:v.summary,body:v.body,categoryIds:v.categoryIds,authorId:v.author.id,authorDisplayName:v.author.displayName,authorAvatarUrl:v.author.avatarUrl,authorVerified:v.author.verified,mediaType:v.mediaType,status:v.status,publishedAt,scheduledFor:v.status==='scheduled'?admin.firestore.Timestamp.fromMillis(v.scheduledMillis):null,updatedAt:now,dailyVisibilityUntil:v.status==='published'&&daily?istanbulEndOfDay():null,youtubeVideoId:v.yt,youtubeUrl:v.yt?`https://www.youtube.com/watch?v=${v.yt}`:null,youtubeThumbnailUrl:v.yt?`https://i.ytimg.com/vi/${v.yt}/hqdefault.jpg`:null,allowComments:body.allowComments!==false,allowLikes:body.allowLikes!==false,allowShare:body.allowShare!==false,...(!id?{createdAt:now,createdBy:adminUid,likeCount:0,commentCount:0}: {})};if(v.mediaType!=='image')Object.assign(data,{imageUrl:null,imageStoragePath:null});await ref.set(data,{merge:true});if(old.imageStoragePath&&v.mediaType!=='image')await deleteStorage(old.imageStoragePath);return{id:ref.id};}
async function adminUploadImage(postId,item){const ref=db().collection(C.posts).doc(clean(postId)),snap=await ref.get();if(!snap.exists)fail('İçerik bulunamadı.',404);const buffer=Buffer.from(clean(item?.base64),'base64');if(buffer.length<100||buffer.length>800*1024)fail('Görsel en fazla 800 KB olabilir.');if(clean(item?.mime)!=='image/jpeg'&&clean(item?.mime)!=='image/webp')fail('Yalnızca optimize JPEG/WebP yüklenebilir.');const bucket=admin.storage().bucket(process.env.BULLETIN_STORAGE_BUCKET||process.env.FIREBASE_STORAGE_BUCKET||'tombikteyze.appspot.com'),path=`bulletin/posts/${postId}/${crypto.randomUUID()}.${item.mime==='image/webp'?'webp':'jpg'}`,token=crypto.randomUUID();await bucket.file(path).save(buffer,{resumable:false,metadata:{contentType:item.mime,cacheControl:'public,max-age=604800',metadata:{firebaseStorageDownloadTokens:token}}});if(snap.get('imageStoragePath'))await deleteStorage(snap.get('imageStoragePath'));const imageUrl=`https://firebasestorage.googleapis.com/v0/b/${encodeURIComponent(bucket.name)}/o/${encodeURIComponent(path)}?alt=media&token=${token}`;await ref.update({mediaType:'image',imageStoragePath:path,imageUrl,youtubeVideoId:null,youtubeUrl:null,youtubeThumbnailUrl:null,updatedAt:admin.firestore.FieldValue.serverTimestamp()});return{imageUrl};}
async function deleteStorage(path){if(!path)return;const bucket=admin.storage().bucket(process.env.BULLETIN_STORAGE_BUCKET||process.env.FIREBASE_STORAGE_BUCKET||'tombikteyze.appspot.com');await bucket.file(path).delete({ignoreNotFound:true}).catch(()=>null);}
async function adminPosts(query={}){let q=db().collection(C.posts).orderBy('createdAt','desc').limit(100);const s=await q.get(),now=Date.now();let docs=s.docs.filter(x=>x.get('status')!=='removed');docs=docs.filter(x=>{const expiry=x.get('dailyVisibilityUntil')?.toMillis?.()||0;return !(x.get('status')==='published'&&(x.get('categoryIds')||[]).includes('daily')&&expiry>0&&expiry<=now);});if(query.status)docs=docs.filter(x=>x.get('status')===query.status);if(query.category)docs=docs.filter(x=>(x.get('categoryIds')||[]).includes(query.category));if(query.search){const n=normalize(query.search);docs=docs.filter(x=>normalize(x.get('title')).includes(n));}return docs.map(x=>postJson(x));}
async function adminPostAction(adminUid,id,action){const ref=db().collection(C.posts).doc(clean(id)),s=await ref.get();if(!s.exists)fail('İçerik bulunamadı.',404);if(action==='publish')await ref.update({status:'published',publishedAt:admin.firestore.FieldValue.serverTimestamp(),dailyVisibilityUntil:(s.get('categoryIds')||[]).includes('daily')?istanbulEndOfDay():null,updatedAt:admin.firestore.FieldValue.serverTimestamp()});else if(action==='unpublish')await ref.update({status:'draft',updatedAt:admin.firestore.FieldValue.serverTimestamp()});else if(action==='remove'){await ref.update({status:'removed',updatedAt:admin.firestore.FieldValue.serverTimestamp()});await deleteStorage(s.get('imageStoragePath'));}else fail('Geçersiz işlem.');await db().collection(C.moderation).add({adminUid,type:'post',targetId:id,action,createdAt:admin.firestore.FieldValue.serverTimestamp()});return{success:true};}
async function adminOverview(){const [all,reports,bans,polls]=await Promise.all([db().collection(C.posts).limit(500).get(),db().collection(C.reports).where('status','==','open').count().get(),db().collection(C.bans).count().get(),db().collection(C.polls).where('status','==','active').count().get()]);const docs=all.docs.filter(x=>x.get('status')==='published'),todayStart=istanbulEndOfDay(Date.now()-86400000).toMillis();return{publishedToday:docs.filter(x=>(x.get('publishedAt')?.toMillis?.()||0)>=todayStart).length,activeDaily:docs.filter(x=>(x.get('categoryIds')||[]).includes('daily')&&(x.get('dailyVisibilityUntil')?.toMillis?.()||0)>Date.now()).length,knowledge:docs.filter(x=>(x.get('categoryIds')||[]).includes('knowledge')).length,relationship:docs.filter(x=>(x.get('categoryIds')||[]).includes('relationship')).length,reportedComments:reports.data().count,bannedUsers:bans.data().count,activePolls:polls.data().count};}
async function adminCreatePoll(uid,body){const question=clean(body.question),raw=Array.isArray(body.options)?body.options:[],options=raw.map((x,i)=>({id:`o${i+1}`,text:clean(x),voteCount:0})).filter(x=>x.text);if(question.length<5||question.length>240||options.length<2||options.length>8)fail('Anket alanları geçersiz.');const hours=Math.min(720,Math.max(1,Number(body.durationHours)||72)),ref=db().collection(C.polls).doc();await ref.set({question,options,status:body.publish===false?'draft':'active',startAt:admin.firestore.FieldValue.serverTimestamp(),endAt:admin.firestore.Timestamp.fromMillis(Date.now()+hours*3600000),createdAt:admin.firestore.FieldValue.serverTimestamp(),createdBy:uid,totalVotes:0,confirmedWinnerOptionId:null});return{id:ref.id};}
async function adminPolls(){const s=await db().collection(C.polls).orderBy('createdAt','desc').limit(100).get();return s.docs.map(x=>({id:x.id,...x.data(),createdAt:millis(x.get('createdAt')),startAt:millis(x.get('startAt')),endAt:millis(x.get('endAt'))}));}
async function adminPollAction(id,action,optionId){const ref=db().collection(C.polls).doc(clean(id));if(action==='close')await ref.update({status:'closed',closedAt:admin.firestore.FieldValue.serverTimestamp()});else if(action==='archive')await ref.update({status:'archived'});else if(action==='confirm')await ref.update({confirmedWinnerOptionId:clean(optionId),status:'closed'});else fail('Geçersiz işlem.');return{success:true};}
async function adminReports(){const s=await db().collection(C.reports).where('status','==','open').orderBy('createdAt','desc').limit(100).get();return s.docs.map(x=>({id:x.id,...x.data(),createdAt:millis(x.get('createdAt'))}));}
async function adminComments(){const s=await db().collectionGroup('comments').orderBy('createdAt','desc').limit(100).get();return s.docs.map(x=>({id:x.id,...x.data(),createdAt:millis(x.get('createdAt'))}));}
async function adminCommentAction(uid,body){const postId=clean(body.postId),commentId=clean(body.commentId),action=clean(body.action),post=db().collection(C.posts).doc(postId),comment=post.collection('comments').doc(commentId);const s=await comment.get();if(!s.exists)fail('Yorum bulunamadı.',404);if(action==='remove'){await db().runTransaction(async tx=>{const c=await tx.get(comment);if(c.get('moderationStatus')==='published'){tx.update(comment,{moderationStatus:'removed',removedAt:admin.firestore.FieldValue.serverTimestamp(),removedBy:uid});tx.update(post,{commentCount:admin.firestore.FieldValue.increment(-1)});}});}else if(action==='ban'){await db().collection(C.bans).doc(s.get('userId')).set({userId:s.get('userId'),reason:clean(body.reason)||'Yönetici kararı',bannedAt:admin.firestore.FieldValue.serverTimestamp(),bannedBy:uid});}else fail('Geçersiz işlem.');return{success:true};}
async function adminReportAction(uid,body){const report=db().collection(C.reports).doc(clean(body.reportId)),s=await report.get();if(!s.exists)fail('Şikâyet bulunamadı.',404);const action=clean(body.action);if(action==='dismiss')await report.update({status:'dismissed',resolvedAt:admin.firestore.FieldValue.serverTimestamp(),resolvedBy:uid});else if(action==='remove'){const post=db().collection(C.posts).doc(s.get('postId')),comment=post.collection('comments').doc(s.get('commentId'));await db().runTransaction(async tx=>{const c=await tx.get(comment);if(c.exists&&c.get('moderationStatus')==='published'){tx.update(comment,{moderationStatus:'removed'});tx.update(post,{commentCount:admin.firestore.FieldValue.increment(-1)});}tx.update(report,{status:'resolved',resolvedAt:admin.firestore.FieldValue.serverTimestamp(),resolvedBy:uid});});}else if(action==='ban'){await db().collection(C.bans).doc(s.get('commenterId')).set({userId:s.get('commenterId'),reason:clean(body.reason)||s.get('reason'),bannedAt:admin.firestore.FieldValue.serverTimestamp(),bannedBy:uid});await report.update({status:'resolved',resolvedAt:admin.firestore.FieldValue.serverTimestamp(),resolvedBy:uid});}else fail('Geçersiz işlem.');return{success:true};}
async function adminBans(){const s=await db().collection(C.bans).orderBy('bannedAt','desc').limit(100).get();return s.docs.map(x=>({id:x.id,...x.data(),bannedAt:millis(x.get('bannedAt'))}));}
async function adminUnban(uid){await db().collection(C.bans).doc(clean(uid)).delete();return{success:true};}
async function cleanupExpired(){const now=admin.firestore.Timestamp.now(),[expired,scheduled]=await Promise.all([db().collection(C.posts).where('status','==','published').where('dailyVisibilityUntil','<=',now).limit(100).get(),db().collection(C.posts).where('status','==','scheduled').where('scheduledFor','<=',now).limit(100).get()]);let removed=0,published=0;for(const doc of scheduled.docs){await doc.ref.update({status:'published',publishedAt:admin.firestore.FieldValue.serverTimestamp(),scheduledFor:null,dailyVisibilityUntil:(doc.get('categoryIds')||[]).includes('daily')?istanbulEndOfDay():null,updatedAt:admin.firestore.FieldValue.serverTimestamp()});published++;}for(const doc of expired.docs){if(!(doc.get('categoryIds')||[]).includes('daily'))continue;await doc.ref.update({status:'removed',dailyVisibilityUntil:null,updatedAt:admin.firestore.FieldValue.serverTimestamp()});await deleteStorage(doc.get('imageStoragePath'));removed++;}return{updated:0,removed,published};}
let timer=null;function startCleanupLoop(){if(timer)return;const run=()=>cleanupExpired().catch(e=>console.error('BULLETIN CLEANUP ERROR:',e.message));void run();timer=setInterval(run,30*60*1000);timer.unref?.();}

module.exports={C,limits,normalize,moderate,youtubeId,istanbulEndOfDay,feed,detail,toggleLike,addComment,reportComment,block,submitContentRequest,adminContentRequests,adminContentRequestAction,activePoll,votePoll,adminSavePost,adminUploadImage,adminPosts,adminPostAction,adminOverview,adminCreatePoll,adminPolls,adminPollAction,adminComments,adminCommentAction,adminReports,adminReportAction,adminBans,adminUnban,cleanupExpired,startCleanupLoop,publishers};
