// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoEZyfII5OgKEWbx5zMNhOJso-z7uQMNk',
    appId: '1:688744850733:web:c78e84eef0b6f50f665fa4',
    messagingSenderId: '688744850733',
    projectId: 'falora35',
    authDomain: 'falora35.firebaseapp.com',
    storageBucket: 'falora35.firebasestorage.app',
    measurementId: 'G-PYF37K87QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kR44bmHL5AAPP6y0DWaK31HJVOdHsvQ',
    appId: '1:688744850733:android:a5dc972019d50950665fa4',
    messagingSenderId: '688744850733',
    projectId: 'falora35',
    storageBucket: 'falora35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSTIsY9a9pa2ykRKKZNkAPBGpvPRABt5M',
    appId: '1:688744850733:ios:3c966b25f7db3391665fa4',
    messagingSenderId: '688744850733',
    projectId: 'falora35',
    storageBucket: 'falora35.firebasestorage.app',
    iosBundleId: 'com.example.falora',
  );
}
