// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVS_DSnsv9V8Rm9NpJLmVTn45Hde7PXs',
    appId: '1:36770284037:web:3928a19e47f183c79ad26c',
    messagingSenderId: '36770284037',
    projectId: 'tombikteyze',
    authDomain: 'tombikteyze.firebaseapp.com',
    storageBucket: 'tombikteyze.firebasestorage.app',
    measurementId: 'G-09K6JZJ6Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhK-xqBUCFsT6KrTDAEs9tDq3jOmQ7l1U',
    appId: '1:36770284037:android:a79e40dd2db2a84a9ad26c',
    messagingSenderId: '36770284037',
    projectId: 'tombikteyze',
    storageBucket: 'tombikteyze.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zGpKEMYF7pHJe-UiiRrOkO3lf_6Jnv8',
    appId: '1:36770284037:ios:4c182193f62c4a2e9ad26c',
    messagingSenderId: '36770284037',
    projectId: 'tombikteyze',
    storageBucket: 'tombikteyze.firebasestorage.app',
    androidClientId: '36770284037-56sbkkc8h1j4kfghjntlfj6dkhjibtek.apps.googleusercontent.com',
    iosClientId: '36770284037-t0ligt8b4c2410gclkdl172vrjs6pfg9.apps.googleusercontent.com',
    iosBundleId: 'com.rrlime.falora',
  );
}
